# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aae7df15e8ca7d1d0b177cabc5e933296cb9a7a8881b2b53b7d8e789ba6a3857cd31ce3c113b516d832ee8a43c2c792ca41534785c5a4d75217a9cb016a49ae

test:
  secret_key_base: 09efc744e91259b567aeaa39e286282513e2cb310d2a94b9bcc48caadb050145699c2bb008c720599698f569296f508d4452b0c758edccc80217cf0ec684c247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
